parameters:
    # `layout` locationId
    layout_id: 54

    # `folder` in the media library containing all the releases
    release_container_location_id: 57
    # `folder` in the media library containing all the betas
    beta_container_location_id: 58

    # `blog` locationId
    blog.location_id: 71
    # `blog_post` limit on the `blog` page
    blog.posts_limit: 10
    # `authors` folder locationId
    blog.authors_container_location_id: 72

# configuration for the CommentsBundle
ez_comments:
    system:
        default:
            default_provider: disqus
            content_comments:
                my_comment_ruleset:
                    enabled: true
                    match:
                        Identifier\ContentType:
                            - blog_post
            disqus:
                shortname: ezplatform-com

# additional Twig configuration
twig:
    globals:
        blogLocationId: '%blog.location_id%'
