parameters:
    layout_id: 54
    # Folder in the media library containing all the releases
    release_container_location_id: 57
    # Folder in the media library containing all the betas
    beta_container_location_id: 58
