services:
    ezplatform.controller.download:
        class: AppBundle\Controller\DownloadController
        arguments:
            - '@ezpublish.api.service.search'
            - '@ezplatform.query_type.latest_releases'
            - '%release_container_location_id%'
            - '%beta_container_location_id%'

    ezplatform.controller.blog:
        class: AppBundle\Controller\BlogController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@ezplatform.query_type.children'
            - '%blog.location_id%'
            - '%blog.posts_limit%'

    ezplatform.query_type.latest_releases:
        class: AppBundle\QueryType\LatestReleasesQueryType
        tags:
            - name: ezpublish.query_type

    ezplatform.query_type.children:
        class: AppBundle\QueryType\ChildrenQueryType
        tags:
            - name: ezpublish.query_type

    ezplatform.twig_extension.field_options:
        class: AppBundle\Twig\FieldOptionsTwigExtension
        arguments:
            - '@ezpublish.api.service.content_type'
        tags:
            - name: twig.extension
